dist: bionic
sudo: OFF
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-snapshot
install:
  - pip install --user conan cmake
script:
  - CXX=/usr/bin/clang++ CC=/usr/bin/clang cmake -DCODE_COVERAGE=ON .
  - cmake -Bbuild -- -j$(nproc)
  - ctest -j$(nproc)
  - bash < (curl -s https://codecov.io/bash) -x /usr/bin/gcov