function(enable_sanitizers pangofin)
  if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    option(CODE_COVERAGE "Enable coverage reports" ON)
    if(CODE_COVERAGE)
      target_compile_options(cfg_options INTERFACE --coverage -O0 -g)
      target_link_libraries(cfg_options INTERFACE --coverage)
    endif()
    set(SANITIZERS "")
    option(ENABLE_SANITIZER_ADDRESS "Enable address sanitizer" OFF)
    if(ENABLE_SANITIZER_ADDRESS)
      list(APPEND SANITIZERS "address")
    endif()
    option(ENABLE_SANITIZER_MEMORY "Enable memory sanitizer" OFF)
    if(ENABLE_SANITIZER_MEMORY)
      list(APPEND SANITIZERS "memory")
    endif()
    option(ENABLE_SANITIZER_UNDEFINED_BEHAVIOR "Enable undefined behavior sanitizer" OFF)
    if(ENABLE_SANITIZER_UNDEFINED_BEHAVIOR)
      list(APPEND SANITIZERS "undefined")
    endif()
    option(ENABLE_SANITIZER_THREAD "Enable thread sanitizer" OFF)
    if(ENABLE_SANITIZER_THREAD)
      list(APPEND SANITIZERS "thread")
    endif()
    list(JOIN SANITIZERS "," SANITIZERS_LIST)
  endif()
  if(SANITIZERS_LIST)
    if(NOT "${SANITIZERS_LIST}" STREQUAL "")
      target_compile_options(${pangofin}
                              INTERFACE -fsanitizers=${SANITIZERS_LIST})
      target_link_libraries(${pangofin}
                              INTERFACE -fsanitizers=${SANITIZERS_LIST})  
    endif()    
  endif()  
endfunction()
